# Generated by Django 4.2.30 on 2026-05-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='document_url',
            field=models.URLField(blank=True, help_text='Optional link to a PDF or resource document', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube embed URL or direct video link', null=True),
        ),
    ]
